WITH DATE_TABLE AS (

SELECT TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS  HOUR_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS WEEKDAY_STARTED_AT,
    {{weekday_or_weekend('STARTED_AT')}} AS DAYTYPE_STARTED_AT,
    {{season('STARTED_AT')}} AS SEASON_STARTED_AT
FROM {{ source('demo_schema', 'bike_raw') }}

) 

SELECT *
FROM DATE_TABLE